global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: scylladb
    static_configs:
      - targets: ["scylla-node1:9180", "scylla-node2:9180", "scylla-node3:9180"]
        labels:
          group: 'scylladbNodes'

