global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: cassandraMetrics
    metrics_path: /metrics
    static_configs:
      - targets: ["cassandra-1:9500", "cassandra-2:9500", "cassandra-3:9500"]
        labels:
          group: 'cassandraNodes'

