[tool.poetry]
name = "scylla-monitoring-docs"
description = "Scylla Monitoring Documentation"
version = "0.1"
authors = ["ScyllaDB Documentation Contributors"]

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "6.0"
pygments = "2.2.0"
recommonmark = "0.7.1"
sphinx-autobuild = "2021.3.14"
Sphinx = "4.3.2"
redirects_cli ="~0.1.2"
sphinx-scylladb-theme = "~1.4.1"
sphinx-multiversion-scylla = "~0.2.11"
sphinx-sitemap = "2.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api" 
